' ******************************************************************************
' swxJRNL.swj - journal recorded on 09/08/14 by GARLAND
' *****************************************************************************
Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long
Dim Annotation As Object
Dim Gtol As Object
Dim DatumTag As Object
Dim FeatureData As Object
Dim Feature As Object
Dim Component As Object
Sub main()

Set swApp = Application.SldWorks

Set Part = swApp.OpenDoc4 ("C:\Users\GARLAND\Documents\Projects\Robotics I\Robotics I 3390 2014\Laser pointer\Servo angle diagrams 2.SLDDRW", 3, 0, "", longstatus)
Set Part = swApp.ActivateDoc ("Servo angle diagrams 2 - Sheet1")
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1233281078717, 0.184673180758, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line40", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line27", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line41", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line36", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line33", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line34", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line37", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line43", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem30@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem32@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem33@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem35@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem36@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1406630524781, 0.1946247230321, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1242911603499, 0.1959087930029, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line25", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line40", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line27", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line41", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line36", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line33", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line34", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line37", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line43", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem30@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem31@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem32@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem33@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem35@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem36@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0.185284483965, 0.125795312816, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1971621311953, 0.1718324810496, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0.1310325276968, 0.1060238950437, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.175332941691, 0.09992456268222, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1377738950437, 0.1853152157434, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line25", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line40", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line27", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line41", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line36", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line33", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line34", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line37", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line43", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem30@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem32@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem33@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem35@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem36@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem38@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0, 0, 0, True, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0.1923468688047, 0.1275320670554, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1900997463557, 0.1583497463557, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line36", "SKETCHSEGMENT", 0.2363262653061, 0.1760057084548, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line37", "SKETCHSEGMENT", 0.1981251836735, 0.1180332090499, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("Line36", "SKETCHSEGMENT", 0.2292638804665, 0.1763267259475, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("Point54", "SKETCHPOINT", 0.1647393644315, 0.1060238950437, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem30@Sheet1", "NOTE", 0.1647393644315, 0.1111601749271, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1746909067055, 0.0996035451895, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem30@Sheet1", "NOTE", 0.1647393644315, 0.1146913673469, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("Line41", "SKETCHSEGMENT", 0.1579979970845, 0.1140493323615, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("Line43", "SKETCHSEGMENT", 0.1647393644315, 0.1146913673469, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0.154145787172, 0.1066659300292, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("DetailItem38@Sheet1", "NOTE", 0.1525406997085, 0.1175805247813, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1602451195335, 0.08997302040816, 0, False, 0, Nothing)
Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line33", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 0, 0.1644183469388, 0.12689003207
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line44", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 0, 0.1647393644315, 0.1230378221574
Part.SetPickMode
Part.ViewZoomtofit2
Part.ViewZoomTo2 0.150322, 0.141657, -2.10151e-015, 0.213884, 0.089652, -1.73836e-015
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Point37", "SKETCHPOINT", 0.1647393644315, 0.1302895577139, 0, False, 0, Nothing)
Part.EditDelete
' MSGBOX
' Sketch endpoints and center points cannot be deleted unless the endpoint is a split point of a curve.

Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line33", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 0, 0.1645911725769, 0.1302097085908
Part.ViewZoomtofit2
Part.CreateLine2 0.1647393644315, 0.1180332090499, 0, 0.2430676326531, 0.1180332090499, 0
Part.CreateLine2 0.1647393644315, 0.1180332090499, 0, 0.1248077743478, 0.1180332090499, 0
Part.SetPickMode
Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line27", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 2, 0, 0.1716763282837, 0.1329893644315
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line46", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 1, 0.1309071067094, 0.1191856122449
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 1, 0.216939794756, 0.1259269795918
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line40", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 0, 0.2342747393624, 0.124642909621
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line39", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 1, 1, 0.2345957568551, 0.1259269795918
Part.SetPickMode
Part.SaveAs2 "C:\Users\GARLAND\Documents\Projects\Robotics I\Robotics I 3390 2014\Laser pointer\Servo angle diagrams new.SLDDRW", 0, FALSE, FALSE
boolstatus = Part.Extension.SelectByID("Line46", "SKETCHSEGMENT", 0.152415278721, 0.1180332090499, 0, False, 0, Nothing)
Part.EditDelete
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line45", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 2, 0, 0.1697502233274, 0.1175805247813
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line45", "SKETCHSEGMENT", 0.1896533078755, 0.1180332090499, 0, False, 0, Nothing)
Part.SetLineStyle "CONTINUOUS"
Part.SetLineWidth 2
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.0217611591875, 0.04984583381924, 0, False, 0, Nothing)
Part.CreateLine2 0.1647393644315, 0.1180332090499, 0, 0.1647393644315, 0.1296253433852, 0
Part.SetLineStyle "CONTINUOUS"
Part.SetLineWidth 2
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.05867817084931, 0.03379495918367, 0, False, 0, Nothing)
Part.CreateLine2 0.1647393644315, 0.1296253433852, 0, 0.2430676326531, 0.1296253433852, 0
Part.SetLineStyle "CONTINUOUS"
Part.SetLineWidth 2
Part.SetPickMode
Part.ClearSelection
boolstatus = Part.Extension.SelectByID("DetailItem36@Sheet1", "NOTE", 0.2220760746394, 0.1230378221574, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Line25", "SKETCHSEGMENT", 0.2430676326531, 0.1060238950437, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.2281754070009, 0.1089130524781, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem33@Sheet1", "NOTE", 0.2204709871758, 0.1496822740525, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.2567459638522, 0.1179015422741, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem35@Sheet1", "NOTE", 0.2301015119572, 0.1445459941691, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.269265646068, 0.1105181399417, 0, False, 0, Nothing)
Part.CreateLine2 0.1452968606413, 0.1180332090499, 0, 0.1452968606413, 0.1012086326531, 0
Part.SetLineStyle "CONTINUOUS"
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1508101912575, 0.05401906122449, 0, False, 0, Nothing)
Part.CreateLine2 0.1647393644315, 0.1180332090499, 0, 0.1647393644315, 0.1015296501458, 0
Part.SetLineStyle "CONTINUOUS"
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1421427189543, 0.04824074635569, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem38@Sheet1", "NOTE", 0.1350803341146, 0.08933098542274, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1536993486919, 0.1487192215743, 0, False, 0, Nothing)
Set Note = Part.InsertNote("A")
If Not Note is Nothing Then
   Note.Angle = 0
   boolstatus = Note.SetBalloon(0, 0)
   Set Annotation = Note.GetAnnotation()
   If Not Annotation is Nothing Then
      longstatus = Annotation.SetLeader2(False, 0, True, False, False, False)
      boolstatus = Annotation.SetPosition(0.1540203661846, 0.09350421282799, 0)
   End If
End If
Part.ClearSelection
Part.WindowRedraw

boolstatus = Part.Extension.SelectByID("DetailItem40@Sheet1", "NOTE", 0.15466240117, 0.09157810787172, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1553044361554, 0.09029403790087, 0, False, 0, Nothing)
Set Note = Part.InsertNote("D2")
If Not Note is Nothing Then
   Note.Angle = 0
   boolstatus = Note.SetBalloon(0, 0)
   Set Annotation = Note.GetAnnotation()
   If Not Annotation is Nothing Then
      longstatus = Annotation.SetLeader2(False, 0, True, False, False, False)
      boolstatus = Annotation.SetPosition(0.1928634828027, 0.10795, 0)
   End If
End If
Part.ClearSelection
Part.WindowRedraw

Part.CreateLine2 0.2430676326531, 0.1180332090499, 0, 0.2702286985461, 0.1180332090499, 0
Part.SetLineStyle "CONTINUOUS"
Part.SetPickMode
Part.ClearSelection
Part.CreateLine2 0.2430676326531, 0.1296253433852, 0, 0.2567459638522, 0.1296253433852, 0
Part.SetLineStyle "CONTINUOUS"
Part.SetPickMode
Part.ClearSelection
Part.CreateLine2 0.2430676326531, 0.1763267259475, 0, 0.2570669813449, 0.1763267259475, 0
Part.SetLineStyle "CONTINUOUS"
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.08435957026622, 0.05883432361516, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem31@Sheet1", "NOTE", 0.1784176956306, 0.07905842565598, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem31@Sheet1", "NOTE", 0.2265703195374, 0.07616926822157, 0, False, 0, Nothing)
Set Note = Part.InsertNote("THETA")
If Not Note is Nothing Then
   Note.Angle = 0
   boolstatus = Note.SetBalloon(0, 0)
   Set Annotation = Note.GetAnnotation()
   If Not Annotation is Nothing Then
      longstatus = Annotation.SetLeader2(False, 0, True, False, False, False)
      boolstatus = Annotation.SetPosition(0.1694292058347, 0.1644490787172, 0)
   End If
End If
Part.ClearSelection
Part.WindowRedraw

boolstatus = Part.Extension.SelectByID("DetailItem42@Sheet1", "NOTE", 0.1742444682254, 0.1612389037901, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1575515586044, 0.1583497463557, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem42@Sheet1", "NOTE", 0.1931845002954, 0.1365205568513, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("DetailItem32@Sheet1", "NOTE", 0.1636508909659, 0.1378046268222, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("Sheet1", "SHEET", 0.1697502233274, 0.1708694285714, 0, False, 0, Nothing)
Part.CreateLine2 0.2702286985461, 0.1180332090499, 0, 0.2702286985461, 0.186920303207, 0
Part.SetPickMode
Part.ClearSelection
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line53", "SKETCHSEGMENT", 0.0, 0.0, 0.0, False, 0, Nothing)
Part.SketchTrim 2, 1, 0.2551408763887, 0.1763267259475
Part.SetPickMode
boolstatus = Part.Extension.SelectByID("Line54", "SKETCHSEGMENT", 0.2702286985461, 0.1647700962099, 0, False, 0, Nothing)
Part.EditDelete
boolstatus = Part.Extension.SelectByID("DetailItem41@Sheet1", "NOTE", 0.1960736577298, 0.1053818600583, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem24@Sheet1", "NOTE", 0.06477750321082, 0.1541765189504, 0, False, 0, Nothing)
boolstatus = Part.Extension.SelectByID("DetailItem20@Sheet1", "NOTE", 0.06895073061607, 0.1211117172012, 0, False, 0, Nothing)
Part.Save2 FALSE
Part.Save2 FALSE
Part.SaveAs2 "C:\Users\GARLAND\Documents\Projects\Robotics I\Robotics I 3390 2014\Laser pointer\Servo angle diagrams new.JPG", 0, TRUE, FALSE
Part.ClearSelection
Set Part = Nothing
swApp.CloseDoc "Servo angle diagrams new - Sheet1"
swApp.ExitApp
End Sub
